# Generated by Django 4.2 on 2026-03-04 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_promocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='descuento_aplicado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='promocion_aplicada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_aplicados', to='clientes.promocion'),
        ),
        migrations.CreateModel(
            name='OportunidadRuleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('registro', 'Registro de cuenta'), ('primer_pedido', 'Primer pedido completado')], max_length=30)),
                ('usada', models.BooleanField(default=False)),
                ('premio', models.CharField(blank=True, max_length=150)),
                ('puntos_otorgados', models.PositiveIntegerField(default=0)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('usada_en', models.DateTimeField(blank=True, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades_ruleta', to='clientes.perfil')),
            ],
            options={
                'ordering': ('-creada_en',),
                'unique_together': {('perfil', 'accion')},
            },
        ),
    ]
