# Generated by Django 4.2 on 2026-03-04 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_pedido_descuento_aplicado_pedido_promocion_aplicada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremioCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PUNTOS', 'Puntos extra'), ('DESCUENTO', 'Descuento en siguiente pedido')], max_length=20)),
                ('descripcion', models.CharField(max_length=160)),
                ('puntos', models.PositiveIntegerField(default=0)),
                ('descuento_porcentaje', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('usado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premios', to='clientes.perfil')),
            ],
            options={
                'ordering': ('-creado_en',),
            },
        ),
    ]
